### ISSUE TITLE
move to ng5

### ISSUE THREAD

**Issue by davidkarlsen** [mcdonaldp2/ng4-configure#1]
Any plans to provide a ng5 compatible version?

**Comment by davidkarlsen** [comment]
@mcdonaldp2 ping?

**Comment by mcdonaldp2** [comment]
Hey @davidkarlsen, my email was sending these notifications to my junk folder -_-

I'll see if I can get this upgraded to ng5

**Comment by mcdonaldp2** [comment]
@davidkarlsen  appears @catrielmuller forked the code and migrated it to angular 5: https://github.com/catrielmuller/ngx-configure

**Comment by catrielmuller** [comment]
Hey @davidkarlsen // @mcdonaldp2 , i currently using ngx-configure (My Fork) in a production site, so far so good. Its great for do a single build for all enviroments. Ping me if you need some help. Cheers
